from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time

def caltech():
    browser = webdriver.Chrome('C:/Users/samagra/Downloads/chromedriver_win32/chromedriver.exe')
    browser.get('https://apply.caltech.edu/account/login')
    time.sleep(10)
    username = browser.find_element_by_id("email")
    password = browser.find_element_by_id("password")
    username.send_keys("Enter username here")
    password.send_keys("Enter password here")
    login_attempt = browser.find_element_by_xpath("//*[@type='submit']")
    login_attempt.submit()
def mit():
    browser = webdriver.Chrome('C:/Users/samagra/Downloads/chromedriver_win32/chromedriver.exe')
    browser.get('https://my.mit.edu/uaweb/login.htm')
    time.sleep(10)
    username = browser.find_element_by_id("loginUser")
    password = browser.find_element_by_id("loginPassword")
    username.send_keys("Enter username here")
    password.send_keys("Enter password here")
    login_attempt = browser.find_element_by_xpath("//*[@type='submit']")
    login_attempt.submit()
def slo():
    browser = webdriver.Chrome('C:/Users/samagra/Downloads/chromedriver_win32/chromedriver.exe')
    browser.get('https://my.calpoly.edu/cas/login?service=https://myportal.calpoly.edu/Login')
    time.sleep(10)
    username = browser.find_element_by_id("Enter username here")
    password = browser.find_element_by_id("password")
    username.send_keys("Enter username here")
    password.send_keys("Enter password here")
    login_attempt = browser.find_element_by_xpath("//*[@type='submit']")
    login_attempt.submit()
def berkeley():
    browser = webdriver.Chrome('C:/Users/samagra/Downloads/chromedriver_win32/chromedriver.exe')
    browser.get('https://apply.berkeley.edu/account/login?r=https%3a%2f%2fapply.berkeley.edu%2fapply%2fstatus')
    time.sleep(10)
    username = browser.find_element_by_id("email")
    password = browser.find_element_by_id("password")
    username.send_keys("Enter username here")
    password.send_keys("Enter password here")
    login_attempt = browser.find_element_by_xpath("//*[@type='submit']")
    login_attempt.submit()

def ucla():
    browser = webdriver.Chrome('C:/Users/samagra/Downloads/chromedriver_win32/chromedriver.exe')
    browser.get('https://www.admission.ucla.edu/myApplication/Login.aspx?ReturnUrl=/MyApplication')
    time.sleep(10)
    lastName = browser.find_element_by_id("ContentPlaceHolder1__txtLastName")
    appID = browser.find_element_by_id("ContentPlaceHolder1__txtApplicationID")
    dateOfBirth = browser.find_element_by_id("ContentPlaceHolder1__txtDateOfBirth")
    cityOfBirth = browser.find_element_by_id("ContentPlaceHolder1__txtCityOfBirth")
    lastName.send_keys("Enter Last name here")
    appID.send_keys("Enter ID here")
    dateOfBirth.send_keys("Enter Date of Birth here")
    cityOfBirth.send_keys("enter city of birth here")
    #login_attempt = browser.find_element_by_xpath("//*[@type='submit']")
    #login_attempt.submit()


def ucsd():
    browser = webdriver.Chrome('C:/Users/samagra/Downloads/chromedriver_win32/chromedriver.exe')
    browser.get('https://beatriton.ucsd.edu/account/login')
    time.sleep(10)
    username = browser.find_element_by_id("email")
    password = browser.find_element_by_id("password")
    username.send_keys("Enter username here")
    password.send_keys("Enter password here")
    login_attempt = browser.find_element_by_xpath("//*[@type='submit']")
    login_attempt.submit()

def uci():
    browser = webdriver.Chrome('C:/Users/samagra/Downloads/chromedriver_win32/chromedriver.exe')
    browser.get('https://login.uci.edu/ucinetid/webauth?return_url=https://services.admissions.uci.edu:8443/cgi-bin/myadmission.cgi?action=loginwebauth')
    time.sleep(10)
    username = browser.find_element_by_id("ucinetid")
    password = browser.find_element_by_id("password")
    username.send_keys("Enter username here")
    password.send_keys("Enter password here")
    #login_attempt = browser.find_element_by_xpath("//*[@type='submit']")
    #login_attempt.submit()
def cornell():
    browser = webdriver.Chrome('C:/Users/samagra/Downloads/chromedriver_win32/chromedriver.exe')
    browser.get('https://decision.applyyourself.com/fl_login.aspx?id=cornellu')
    time.sleep(10)
    username = browser.find_element_by_id("ctl00_cphDecision_txtUserID")
    password = browser.find_element_by_id("ctl00_cphDecision_txtPassword")
    username.send_keys("Enter username here")
    password.send_keys("Enter password here")
    login_attempt = browser.find_element_by_xpath("//*[@type='submit']")
    login_attempt.submit()
def harvard():
    browser = webdriver.Chrome('C:/Users/samagra/Downloads/chromedriver_win32/chromedriver.exe')
    browser.get('https://apply.college.harvard.edu/account/login')
    time.sleep(10)
    username = browser.find_element_by_id("email")
    password = browser.find_element_by_id("password")
    username.send_keys("Enter username here")
    password.send_keys("Enter password here")
    login_attempt = browser.find_element_by_xpath("//*[@type='submit']")
    login_attempt.submit()
def princeton():
    browser = webdriver.Chrome('C:/Users/samagra/Downloads/chromedriver_win32/chromedriver.exe')
    browser.get('https://apply.princeton.edu/account/login')
    time.sleep(10)
    username = browser.find_element_by_id("email")
    password = browser.find_element_by_id("password")
    username.send_keys("Enter username here")
    password.send_keys("Enter password here")
    #login_attempt = browser.find_element_by_xpath("//*[@type='submit']")
    #login_attempt.submit()
def penn():
    browser = webdriver.Chrome('C:/Users/samagra/Downloads/chromedriver_win32/chromedriver.exe')
    browser.get('https://key.admissions.upenn.edu/account/login')
    time.sleep(10)
    username = browser.find_element_by_id("email")
    password = browser.find_element_by_id("password")
    username.send_keys("Enter username here")
    password.send_keys("Enter password here")
    #login_attempt = browser.find_element_by_xpath("//*[@type='submit']")
    #login_attempt.submit()


def rice():
    browser = webdriver.Chrome('C:/Users/samagra/Downloads/chromedriver_win32/chromedriver.exe')
    browser.get('https://riceadmission.rice.edu/account/login')
    time.sleep(10)
    username = browser.find_element_by_id("email")
    password = browser.find_element_by_id("password")
    username.send_keys("Enter username here")
    password.send_keys("Enter password here")
    login_attempt = browser.find_element_by_xpath("//*[@type='submit']")
    login_attempt.submit()

def michigan():
    browser = webdriver.Chrome('C:/Users/samagra/Downloads/chromedriver_win32/chromedriver.exe')
    browser.get('https://weblogin.umich.edu/?cosign-csprod.dsc&https://csprod.dsc.umich.edu/psp/csprodnonop/EMPLOYEE/HRMS/c/M_HE_NPS_SELF_SERVICES.M_HE_SSS_NPSCENTER.GBL?PORTALPARAM_PTCNAV=M_HE_SSS_NPSCENTER_GBL&EOPP.SCNode=HRMS&EOPP.SCPortal=EMPLOYEE&EOPP.SCName=CO_EMPLOYEE_SELF_SERVICE&EOPP.SCLabel=Self%20Service&EOPP.SCPTfname=CO_EMPLOYEE_SELF_SERVICE&FolderPath=PORTAL_ROOT_OBJECT.CO_EMPLOYEE_SELF_SERVICE.M_HE_SSS_NPSCENTER_GBL&IsFolder=false&authType=3N')
    time.sleep(10)
    username = browser.find_element_by_id("login")
    password = browser.find_element_by_id("password")
    username.send_keys("Enter username here")
    password.send_keys("Enter password here")
    login_attempt = browser.find_element_by_xpath("//*[@type='submit']")
    login_attempt.submit()

def cmu():
    browser = webdriver.Chrome('C:/Users/samagra/Downloads/chromedriver_win32/chromedriver.exe')
    browser.get('https://www.as.cmu.edu/application//display.html')
    time.sleep(10)
    ID = browser.find_element_by_id("admissionId")
    lastName = browser.find_element_by_id("lastName")
    birthDate = browser.find_element_by_id("birthDate")
    ID.send_keys("Enter username here")
    lastName.send_keys("Enter Last name here")
    birthDate.send_keys("Enter DoB here")
    login_attempt = browser.find_element_by_xpath("//*[@type='submit']")
    login_attempt.submit()


